### ISSUE TITLE
Blabbermouth doesn't support syslog

### ISSUE THREAD

**Issue by solidsnack** [markrebec/blabbermouth#2]

**Comment by markrebec** [comment]
Any particular requests on how you'd like a syslog bystander to work? Configuration options for output file(s), etc?

Would it be worth also/alternately creating something that can dump to a generic IO stream?

**Comment by solidsnack** [comment]
This wouldn't log to files, but rather directly, via the Syslog module

http://ruby-doc.org/stdlib-2.2.0/libdoc/syslog/rdoc/Syslog.html

**Comment by kwent** [comment]
Maybe https://github.com/markrebec/blabbermouth/pull/3 is a good start...

**Comment by markrebec** [comment]
Oh yeah, duh. This should be no problem - will find a chunk of time to wrap and release it today.

**Comment by markrebec** [comment]
There is now a `blabbermouth-syslog` gem that provides the syslog bystander, provided by #4 and available in [0.0.13](https://rubygems.org/gems/blabbermouth/versions/0.0.13).
