### ISSUE TITLE
Syslog bystander message format

### ISSUE THREAD

**Issue by kwent** [markrebec/blabbermouth#7]
Hi,

The message format for the **syslog bystander** is wrong.

For example, **Timestamp and Syslog Lvl** is repeated in the body message. 

``` plain
Jul 06 14:59:10 myserver.mydomain blabbermouth:  [2015/07/06 14:59:10 PDT] Blabbermouth.info: syslog message {data: data}
```

Regards,

**Comment by markrebec** [comment]
Hey @kwent! This has been updated to remove the duplicate timestamp and is available in `>= 0.1.4` of `blabbermouth-syslog`.
