### ISSUE TITLE
Rollbar Log levels

### ISSUE THREAD

**Issue by kwent** [markrebec/blabbermouth#8]
Add more Rollbar log levels

``` plain
You can use one of Rollbar.log(level, ...), Rollbar.debug(), Rollbar.info(), Rollbar.warning(), Rollbar.error() and Rollbar.critical() to report exceptions and messages.
```

Cf. https://github.com/rollbar/rollbar-gem#caught-exceptions-and-messages

Blabbermouth only support info and error.

**Comment by markrebec** [comment]
Hey @kwent! This has been added and is available in `>= 0.1.4` of `blabbermouth` and `blabbermouth-rollbar`. Sorry it took so long to get back to this!
